### ISSUE TITLE
ByteUtils问题

### ISSUE THREAD

**Issue by yanquanyu** [thlcly/Mini-JVM#1]
`byteToInteger`方法判断4个字节的地方应该是有问题，最后和`0XFF`做逻辑与操作，高24位全部都变成0了。
```
return   b[3] & 0xFF | (b[2] & 0xFF) << 8 | (b[1] & 0xFF) << 16 | (b[0] & 0xFF) << 24;
```

**Comment by thlcly** [comment]
@yanquanyu 是的，需要修改. 同时还需要修改2个字节的转换, 但是不能直接用你说的那个方法, 因为需要是无符号整形, 所以对于四个字节的byte[]需要转成long

**Comment by thlcly** [comment]
@yanquanyu 是的，需要修改. 同时还需要修改2个字节的转换, 但是不能直接用你说的那个方法, 因为需要是无符号整形, 所以对于四个字节的byte[]需要转成long
